version: '2'
services:
  install:
    image: starefossen/github-pages
    volumes:
      - /root/.gem
      - /usr/local/lib/ruby/gems
      - /usr/local/bundle
      - ./:/usr/src/app
    command: bundle install
  serve:
    image: starefossen/github-pages
    volumes_from:
      - install
    ports:
      - "4000:4000"
#    environment:
#      -e JEKYLL_GITHUB_TOKEN=my-github-token \
# COMMAND is copied from Dockerfile, with the addition of --incremental
    command: jekyll serve -d /_site --incremental --watch --force_polling -H 0.0.0.0 -P 4000
